Created new functions to manage reference entities
php-etl/akeneo-expression-language pull request #13
Opened 2023-05-25 13:01 UTC by sebprt

2023-05-26 10:20 UTC, clemzarch commented on src/AkeneoBuilderProvider.php
> +            new WithReferenceEntitySimpleOption('withReferenceEntitySimpleOption'),
fait une PR dans la doc sinon on va les oublier

2023-06-23 09:33 UTC, clemzarch approved these changes

2023-06-23 09:36 UTC, gplanchat requested changes

2023-06-23 09:36 UTC, gplanchat commented on src/WithSimpleOption.php
> +    private function evaluate(array $context, string $code, string $attribute, array $labels, string|null $locale = null, string|null $scope = null): array
```suggestion
    private function evaluate(array $context, string $code, string $attribute, array $labels, string $locale = 'null', string $scope = 'null'): array
```

2023-06-23 09:36 UTC, gplanchat commented on src/WithValue.php
> +    private function evaluate(array $context, string $value, string|null $locale = null, string|null $scope = null): array
```suggestion
    private function evaluate(array $context, string $value, string $locale = 'null', string $scope = 'null'): array
```

2023-06-23 09:37 UTC, merged